"""add MES MNQ symbols

Revision ID: af138ef468ba
Revises: 4de8f38292c9
Create Date: 2026-04-05 19:19:17.651825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af138ef468ba'
down_revision: Union[str, Sequence[str], None] = '4de8f38292c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add MES and MNQ to the symbolenum type."""
    op.execute("ALTER TYPE symbolenum ADD VALUE IF NOT EXISTS 'MES'")
    op.execute("ALTER TYPE symbolenum ADD VALUE IF NOT EXISTS 'MNQ'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
