"""initial schema

Revision ID: d9d20db64dbb
Revises: 
Create Date: 2026-04-02 23:58:14.127064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9d20db64dbb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('symbol', sa.Enum('ES', 'NQ', name='symbolenum'), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('bid', sa.Float(), nullable=False),
    sa.Column('ask', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('market_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('symbols', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('sentiment', sa.Enum('BULLISH', 'BEARISH', 'NEUTRAL', name='sentimentenum'), nullable=True),
    sa.Column('impact_rating', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='impactratingenum'), nullable=True),
    sa.Column('analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_significant', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('strategy_name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.Enum('ES', 'NQ', name='symbolenum'), nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_type', sa.Enum('STARTUP', 'SHUTDOWN', 'DISCONNECT', 'RECONNECT', 'RECONCILIATION', 'ERROR', name='systemeventtypeenum'), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('strategy_name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.Enum('ES', 'NQ', name='symbolenum'), nullable=False),
    sa.Column('direction', sa.Enum('LONG', 'SHORT', name='directionenum'), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('reasoning', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['market_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('EXECUTE', 'REJECT', 'MODIFY', 'DEFER', name='decisionactionenum'), nullable=False),
    sa.Column('risk_evaluation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decision_reasoning', sa.Text(), nullable=False),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_id')
    )
    op.create_table('signal_news',
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('news_event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['news_event_id'], ['news_events.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('signal_id', 'news_event_id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.Enum('ES', 'NQ', name='symbolenum'), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='ordersideenum'), nullable=False),
    sa.Column('order_type', sa.Enum('MARKET', 'LIMIT', 'STOP', 'STOP_LIMIT', name='ordertypeenum'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('limit_price', sa.Float(), nullable=True),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('ib_order_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SUBMITTED', 'FILLED', 'CANCELLED', 'REJECTED', name='orderstatusenum'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.Enum('ES', 'NQ', name='symbolenum'), nullable=False),
    sa.Column('direction', sa.Enum('LONG', 'SHORT', name='directionenum'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('entry_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entry_decision_id', sa.Integer(), nullable=True),
    sa.Column('exit_decision_id', sa.Integer(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['entry_decision_id'], ['decisions.id'], ),
    sa.ForeignKeyConstraint(['exit_decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('fill_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('commission', sa.Float(), nullable=False),
    sa.Column('slippage', sa.Float(), nullable=False),
    sa.Column('ib_execution_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('protective_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('stop_order_id', sa.Integer(), nullable=True),
    sa.Column('target_order_id', sa.Integer(), nullable=True),
    sa.Column('stop_ib_order_id', sa.Integer(), nullable=True),
    sa.Column('target_ib_order_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'TRIGGERED', 'CANCELLED', name='protectiveorderstatusenum'), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['stop_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['target_order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_outcomes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=False),
    sa.Column('r_multiple', sa.Float(), nullable=True),
    sa.Column('hold_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('entry_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('exit_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('analysis_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entry_snapshot_id'], ['market_snapshots.id'], ),
    sa.ForeignKeyConstraint(['exit_snapshot_id'], ['market_snapshots.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_outcomes')
    op.drop_table('protective_orders')
    op.drop_table('fills')
    op.drop_table('positions')
    op.drop_table('orders')
    op.drop_table('signal_news')
    op.drop_table('decisions')
    op.drop_table('signals')
    op.drop_table('system_events')
    op.drop_table('strategy_logs')
    op.drop_table('news_events')
    op.drop_table('market_snapshots')
    # ### end Alembic commands ###
